/* Casos de test del Level 3 de ESTA app (Past Tenses).
   full: respuesta modelo SIN contracciones (de ella salen las variantes contraídas)
   pos:  variantes que deben ACEPTARSE · neg: respuestas incorrectas que deben FALLAR */
module.exports = {
  ps_l3_0: { full: "Yesterday I went to the cinema with my friends.",
    pos: ["I went to the cinema with my friends yesterday.", "I went to the cinema yesterday with my friends.", "Yesterday I went to the movies with my friends",
          "I went to the movie theater with my friends yesterday", "Yesterday, I went to the pictures with my friends!"],
    neg: ["Yesterday I go to the cinema with my friends.", "Yesterday I goed to the cinema with my friends.", "Yesterday I have gone to the cinema with my friends.",
          "Yesterday I was go to the cinema with my friends.", "I went cinema to the with my friends yesterday.", "Yesterday I went to cinema with my friends.",
          "Yesterday I went at the cinema with my friends."] },
  ps_l3_1: { full: "We did not see Pedro at the party.",
    pos: ["We didn't see Pedro at the party.", "We didnt see pedro at the party"],
    neg: ["We didn't saw Pedro at the party.", "We don't see Pedro at the party.", "We haven't seen Pedro at the party.", "We didn't see Pedro in the party.",
          "We not saw Pedro at the party.", "We didn't see to Pedro at the party.", "Pedro didn't see us at the party."] },
  ps_l3_2: { full: "Where did you buy that jacket?",
    pos: ["where did you buy that jacket", "WHERE DID YOU BUY THAT JACKET?"],
    neg: ["Where did you bought that jacket?", "Where you bought that jacket?", "Where have you bought that jacket?", "Where did you buy this jacket?",
          "Where do you buy that jacket?", "Where did you buyed that jacket?"] },
  ps_l3_3: { full: "My grandmother was born in 1950.",
    pos: ["My grandma was born in 1950.", "My granny was born in nineteen fifty.", "My nan was born in 1950"],
    neg: ["My grandmother born in 1950.", "My grandmother is born in 1950.", "My grandmother was born on 1950.", "My grandmother has been born in 1950.",
          "My grandmother were born in 1950.", "My grandmother was born in 1960.", "My grandmother borned in 1950."] },
  ps_l3_4: { full: "Two years ago we lived in Huesca.",
    pos: ["We lived in Huesca two years ago.", "Two years ago we were living in Huesca.", "We used to live in Huesca two years ago.", "2 years ago we lived in Huesca"],
    neg: ["We lived in Huesca since two years.", "We live in Huesca two years ago.", "We have lived in Huesca two years ago.", "Two years ago we lived on Huesca.",
          "We lived in Huesca for two years ago.", "Two years ago we use to live in Huesca.", "Two years before we lived in Huesca."] },
  ps_l3_5: { full: "The exam was very difficult.",
    pos: ["The exam was really hard.", "The test was very difficult.", "The exam was very hard!"],
    neg: ["The exam were very difficult.", "The exam is very difficult.", "The exam has been very difficult.", "The exam was very difficulty.",
          "Was the exam very difficult.", "The exam was very dificult.", "The exam very difficult."] },
  ps_l3_6: { full: "When I was little, I played football every day.",
    pos: ["When I was a child, I used to play football every day.", "I played football every day when I was little.", "When I was small I would play soccer every day",
          "As a child, I played football every day.", "When I was a little boy, I used to play football every day."],
    neg: ["When I was little, I play football every day.", "When I am little, I played football every day.", "When I was little, I was playing football every day.",
          "When I was little, I have played football every day.", "When I was little, I use to play football every day.", "When I was little, I used to playing football every day.",
          "When I was little, I played to football every day."] },
  ps_l3_7: { full: "Did you call your mother last night?",
    pos: ["Did you phone your mum last night?", "Did you ring your mother last night?", "Last night, did you call your mom?"],
    neg: ["Did you called your mother last night?", "Have you called your mother last night?", "You called your mother last night?", "Did you call to your mother last night?",
          "Do you call your mother last night?", "Did you call your mother tonight?"] },
  ps_l3_8: { full: "They missed the bus and arrived late for class.",
    pos: ["They missed the bus and were late for class.", "They missed the bus and got to school late.", "They missed the bus and they arrived late to class.",
          "They missed the bus and came late to school."],
    neg: ["They lost the bus and arrived late for class.", "They missed the bus and arrive late for class.", "They miss the bus and arrived late for class.",
          "They missed the bus and arrived late in class.", "They missed the bus and arrived lately for class.", "They missed the bus and arrived late."] },
  ps_l3_9: { full: "He did not do his homework.",
    pos: ["She didn't do her homework.", "He didn't do the homework.", "She did not do the homework"],
    neg: ["He didn't did his homework.", "He didn't made his homework.", "He doesn't do his homework.", "He not did his homework.", "Didn't do his homework.",
          "He didn't do her homework.", "He didn't do his homeworks."] },

  pc_l3_0: { full: "At nine o'clock at night I was studying.",
    pos: ["I was studying at nine in the evening.", "At 9 pm I was studying.", "At 21:00 I was studying.", "At nine at night I was studying", "She was studying at nine at night.",
          "At 9 p.m. I was studying"],
    neg: ["At nine at night I studied.", "At nine at night I was study.", "At nine at night I were studying.", "At nine at night I am studying.",
          "At nine at night I have been studying.", "At nine at night was studying."] },
  pc_l3_1: { full: "It was raining when we left home.",
    pos: ["It was raining when we left the house.", "When we went out, it was raining.", "It was raining when we left our house", "When we left home it was raining"],
    neg: ["It rained when we left home.", "Was raining when we left home.", "It was raining when we leaved home.", "It was rain when we left home.",
          "It was raining when we have left home.", "It was raining when we left from home.", "It is raining when we left home."] },
  pc_l3_2: { full: "What were you doing at five yesterday?",
    pos: ["What were you doing yesterday at five?", "What were you doing at five o'clock yesterday afternoon?", "What were you doing at 5 yesterday?",
          "Yesterday at five, what were you doing?", "What were you doing yesterday at five in the afternoon?"],
    neg: ["What did you do at five yesterday?", "What were you do at five yesterday?", "What you were doing at five yesterday?", "What was you doing at five yesterday?",
          "What are you doing at five yesterday?", "What were you making at five yesterday?"] },
  pc_l3_3: { full: "While I was cooking, my brother was watching TV.",
    pos: ["As I was cooking, my brother was watching television.", "My brother was watching TV while I was cooking.", "While I cooked, my brother watched TV.",
          "While I was cooking my brother was watching the TV"],
    neg: ["While I cooking, my brother watching TV.", "While I was cooking, my brother watches TV.", "While I was cook, my brother was watching TV.",
          "While I was cooking, my brother was seeing TV.", "While I was cooking, my brother were watching TV.", "During I was cooking, my brother was watching TV."] },
  pc_l3_4: { full: "They were not listening to the teacher.",
    pos: ["They weren't listening to the teacher.", "They werent listening to the teacher"],
    neg: ["They weren't listening the teacher.", "They didn't listening to the teacher.", "They wasn't listening to the teacher.", "They weren't listen to the teacher.",
          "They aren't listening to the teacher.", "They weren't hearing the teacher."] },
  pc_l3_5: { full: "Were you sleeping when I called you?",
    pos: ["Were you asleep when I phoned you?", "Were you sleeping when I rang?", "were you sleeping when i called"],
    neg: ["Were you sleeping when I was calling you?", "Was you sleeping when I called you?", "Did you sleep when I called you?", "Were you sleeping when I call you?",
          "You were sleeping when I called you?", "Were you sleep when I called you?"] },
  pc_l3_6: { full: "The sun was shining and the children were playing in the park.",
    pos: ["It was sunny and the children were playing in the park.", "It was sunny and the kids were playing in the park.", "The sun was shining and the children played in the park."],
    neg: ["It made sun and the children were playing in the park.", "The sun was shine and the children were playing in the park.", "The sun was shining and the children was playing in the park.",
          "The sun shining and the children playing in the park.", "It was sunny and the children are playing in the park.", "It was sunny and the childrens were playing in the park."] },
  pc_l3_7: { full: "Yesterday afternoon I was working in the garden.",
    pos: ["I was working in the garden yesterday afternoon.", "Yesterday afternoon I worked in the garden.", "Yesterday evening I was working in the garden."],
    neg: ["Yesterday afternoon I was work in the garden.", "Yesterday afternoon I have been working in the garden.", "Yesterday afternoon I was working on the garden.",
          "Yesterday afternoon I were working in the garden.", "Yesterday afternoon I am working in the garden.", "Yesterday afternoon I was working in the garden tomorrow."] },
  pc_l3_8: { full: "My sister was not wearing a coat.",
    pos: ["My sister wasn't wearing a coat.", "My sister didn't have a coat on.", "My sister didn't wear a coat."],
    neg: ["My sister wasn't carrying a coat.", "My sister wasn't wear a coat.", "My sister didn't wearing a coat.", "My sister weren't wearing a coat.",
          "My sister isn't wearing a coat.", "My sister wasn't wearing coat."] },
  pc_l3_9: { full: "Why were you laughing?",
    pos: ["why were you laughing", "Why were you laughing??"],
    neg: ["Why you were laughing?", "Why were you laugh?", "Why was you laughing?", "Why did you laughing?", "Why are you laughing?", "Why were you laughting?"] },

  pp_l3_0: { full: "When I arrived, the film had already started.",
    pos: ["When I got there, the movie had already begun.", "The film had already started when I arrived.", "When I arrived the film had started already",
          "By the time I got to the cinema, the film had already started."],
    neg: ["When I arrived, the film already started.", "When I arrived, the film has already started.", "When I had arrived, the film already started.",
          "When I arrived, the film had already start.", "When I arrived, the film had already began.", "When I arrived, the film was already started."] },
  pp_l3_1: { full: "I had never seen snow before.",
    pos: ["I had never seen the snow before.", "I had never seen snow.", "I'd never seen snow before", "She had never seen snow before."],
    neg: ["I had never saw snow before.", "I have never seen snow before.", "I never had seen snow before.", "I had ever seen snow before.", "I hadn't never seen snow before.",
          "I had never see snow before."] },
  pp_l3_2: { full: "She was sad because she had lost her dog.",
    pos: ["He was sad because he had lost his dog.", "She was unhappy because she had lost her dog.", "She was sad as she'd lost her dog"],
    neg: ["She was sad because she has lost her dog.", "She was sad because she lost her dog.", "She was sad because she had lost to her dog.",
          "She was sad because she had lose her dog.", "She were sad because she had lost her dog.", "She was sad because she had lost his dog."] },
  pp_l3_3: { full: "Had you been to Italy before that trip?",
    pos: ["Had you ever been to Italy before that trip?", "Had you visited Italy before that journey?", "Had you been in Italy before that holiday?"],
    neg: ["Have you been to Italy before that trip?", "Had you be to Italy before that trip?", "Did you been to Italy before that trip?", "You had been to Italy before that trip?",
          "Had you been to Italy after that trip?", "Had you gone to Italy before that trip?"] },
  pp_l3_4: { full: "When we got to the station, the train had already left.",
    pos: ["When we arrived at the station, the train had already gone.", "The train had already left when we got to the station.",
          "By the time we reached the station, the train had left already."],
    neg: ["When we got to the station, the train already left.", "When we arrived to the station, the train had already left.", "When we got to the station, the train had already leaved.",
          "When we got to the station, the train has already left.", "When we get to the station, the train had already left.", "When we got to the station, the train had already went."] },
  pp_l3_5: { full: "They had not finished their homework when the teacher arrived.",
    pos: ["They hadn't finished their homework when the teacher came in.", "When the teacher arrived, they hadn't finished their homework.", "They hadn't finished the homework yet when the teacher arrived."],
    neg: ["They didn't finish their homework when the teacher arrived.", "They hadn't finish their homework when the teacher arrived.", "They haven't finished their homework when the teacher arrived.",
          "They hadn't finished their homework when the teacher had arrived.", "They hadn't finished their homeworks when the teacher arrived.", "They hadn't finished their homework when the teacher arrives."] },
  pp_l3_6: { full: "We had already eaten when they called us.",
    pos: ["We had already had lunch when they phoned us.", "When they called us, we had already eaten.", "We'd already eaten when they rang", "We had eaten already when they called us"],
    neg: ["We already ate when they called us.", "We had already ate when they called us.", "We have already eaten when they called us.", "We had already eaten when they had called us.",
          "We had eaten already when they call us.", "We had already eat when they called us."] },
  pp_l3_7: { full: "I realised that I had left my mobile at home.",
    pos: ["I realized I had left my phone at home.", "I realised I'd left my mobile phone at home.", "I realized that I had left my cell phone at home"],
    neg: ["I realised that I have left my mobile at home.", "I realised that I left my mobile at home.", "I realised of that I had left my mobile at home.",
          "I realise that I had left my mobile at home.", "I realised that I had leave my mobile at home.", "I realised that I had left my mobile in home."] },
  pp_l3_8: { full: "I had not read the book before the exam.",
    pos: ["I hadn't read the book before the exam.", "She hadn't read the book before the test.", "I hadnt read the book before the exam"],
    neg: ["I didn't read the book before the exam.", "I hadn't readed the book before the exam.", "I haven't read the book before the exam.",
          "I hadn't read the book before of the exam.", "I hadn't to read the book before the exam.", "I hadn't read the book after the exam."] },
  pp_l3_9: { full: "Had they already closed the shop when you arrived?",
    pos: ["Had they closed the shop already when you got there?", "Had the shop already closed when you arrived?", "Had they closed the store when you arrived?"],
    neg: ["Did they already close the shop when you arrived?", "Had they already close the shop when you arrived?", "Have they already closed the shop when you arrived?",
          "They had already closed the shop when you arrived?", "Had they already closed the shop when you had arrived?", "Had they already closed the shop when you arrive?"] },

  spp_l3_0: { full: "I have never been to London.",
    pos: ["I've never been to London.", "I have never visited London.", "I have never been in London"],
    neg: ["I have never be to London.", "I never was in London.", "I had never been to London.", "I have ever been to London.", "I have never went to London.",
          "I haven't never been to London."] },
  spp_l3_1: { full: "I went to London last summer.",
    pos: ["Last summer I went to London.", "I visited London last summer.", "Last summer, I was in London."],
    neg: ["I have been to London last summer.", "I go to London last summer.", "I went to London the last summer.", "I was go to London last summer.",
          "I went London last summer.", "I have gone to London last summer."] },
  spp_l3_2: { full: "Have you seen Juan today?",
    pos: ["Have you seen juan today", "HAVE YOU SEEN JUAN TODAY?"],
    neg: ["Have you saw Juan today?", "Did you see Juan today?", "Have you seen to Juan today?", "Has you seen Juan today?", "You have seen Juan today?", "Have you seen Juan yesterday?"] },
  spp_l3_3: { full: "When did you start studying English?",
    pos: ["When did you begin to learn English?", "When did you start to study English?", "When did you start learning English"],
    neg: ["When have you started studying English?", "When did you started studying English?", "When you started studying English?", "When did you start study English?",
          "When did you start to studying English?", "When do you start studying English?"] },
  spp_l3_4: { full: "I have lived in this village since 2015.",
    pos: ["I have been living in this town since 2015.", "I've lived in this village since 2015.", "Since 2015 I have lived in this village.",
          "I've been living in this village since two thousand and fifteen"],
    neg: ["I live in this village since 2015.", "I have lived in this village for 2015.", "I am living in this village since 2015.", "I lived in this village since 2015.",
          "I have lived in this village from 2015.", "I have live in this village since 2015."] },
  spp_l3_5: { full: "I lived in Madrid for three years, but now I live in Huesca.",
    pos: ["I lived in Madrid for three years, but I live in Huesca now.", "I lived in Madrid three years but I now live in Huesca", "I lived in Madrid for 3 years, but I live in Huesca."],
    neg: ["I have lived in Madrid for three years, but now I live in Huesca.", "I lived in Madrid since three years, but now I live in Huesca.",
          "I lived in Madrid during three years, but now I live in Huesca.", "I lived in Madrid for three years, but now I lived in Huesca.",
          "I live in Madrid for three years, but now I live in Huesca.", "I lived in Madrid for three years, but now I lives in Huesca."] },
  spp_l3_6: { full: "We have had two exams this week.",
    pos: ["This week we have had two exams.", "We've had two tests this week.", "Weve had 2 exams this week"],
    neg: ["We have two exams this week.", "We had two exams this week.", "We have have two exams this week.", "We has had two exams this week.", "We have had two exam this week.",
          "We have had two exams last week."] },
  spp_l3_7: { full: "My father has lost his glasses and he can not read.",
    pos: ["My dad has lost his glasses so he can't read.", "My father has lost his glasses and can't read.", "My father has lost his glasses and he cannot read.",
          "My father's lost his glasses and he cant read"],
    neg: ["My father lost his glasses and he can't read.", "My father has lost his glasses and he can't to read.", "My father has losed his glasses and he can't read.",
          "My father have lost his glasses and he can't read.", "My father has lost his glasses and he doesn't can read.", "My father has lost her glasses and he can't read."] },
  spp_l3_8: { full: "Mozart composed more than 600 works.",
    pos: ["Mozart wrote over 600 pieces of music.", "Mozart composed more than six hundred works.", "Mozart composed over 600 compositions"],
    neg: ["Mozart has composed more than 600 works.", "Mozart composed more of 600 works.", "Mozart compose more than 600 works.", "Mozart composed more that 600 works.",
          "Mozart composed 600 works.", "Mozart composed more than 60 works."] },
  spp_l3_9: { full: "Have you ever missed a flight?",
    pos: ["Have you ever missed a plane?", "have you ever missed a flight"],
    neg: ["Have you ever lost a plane?", "Did you ever miss a plane?", "Have you ever miss a plane?", "Have you never missed a plane?", "Has you ever missed a flight?",
          "You have ever missed a flight?"] },

  spc_l3_0: { full: "I was having dinner when the phone rang.",
    pos: ["When the phone rang, I was having dinner.", "She was having dinner when the phone rang.", "I was eating dinner when the phone rang", "I was having supper when the phone rang."],
    neg: ["I had dinner when the phone rang.", "I was having dinner when the phone rung.", "I was having dinner when the phone sounded.", "I was have dinner when the phone rang.",
          "I were having dinner when the phone rang.", "I was having dinner when the phone ringed."] },
  spc_l3_1: { full: "While I was walking in the park, I saw my teacher.",
    pos: ["I saw my teacher while I was walking through the park.", "As I was walking around the park, I saw my teacher.", "While walking in the park, I saw my teacher."],
    neg: ["While I walked in the park, I was seeing my teacher.", "While I was walking in the park, I have seen my teacher.", "While I was walking in the park, I saw to my teacher.",
          "While I was walk in the park, I saw my teacher.", "While I was walking in the park, I seed my teacher.", "While I was walking in the park, I see my teacher."] },
  spc_l3_2: { full: "When the police arrived, the thieves escaped.",
    pos: ["When the police came, the robbers ran away.", "The thieves escaped when the police arrived.", "When the police got there the thieves got away"],
    neg: ["When the police arrived, the thieves were escaping.", "When the police arrived, the thieves had escaped.", "When the police arrived, the thieves escaped themselves.",
          "When the police arrive, the thieves escaped.", "When the police arrived, the thiefs escaped.", "When the police arrived, the thieves escape."] },
  spc_l3_3: { full: "When the police arrived, the thieves were escaping.",
    pos: ["When the police came, the robbers were running away.", "The thieves were escaping when the police arrived.", "When the police got there, the thieves were getting away."],
    neg: ["When the police arrived, the thieves escaped.", "When the police arrived, the thieves was escaping.", "When the police arrived, the thieves had escaped.",
          "When the police arrived, the thieves were escape.", "When the police was arriving, the thieves were escaping.", "When the police arrived, the thieves are escaping."] },
  spc_l3_4: { full: "She broke her leg while she was skiing.",
    pos: ["He broke his leg while he was skiing.", "She broke her leg while skiing.", "While she was skiing, she broke her leg."],
    neg: ["She broke the leg while she was skiing.", "She broke her leg while she skied.", "She was breaking her leg while she was skiing.", "She broke herself the leg while she was skiing.",
          "She breaked her leg while she was skiing.", "She broke his leg while she was skiing."] },
  spc_l3_5: { full: "What were you doing when the lights went out?",
    pos: ["What were you doing when there was a power cut?", "What were you doing when the power went off?", "When the lights went out, what were you doing?"],
    neg: ["What did you do when the lights went out?", "What were you doing when the lights were going out?", "What you were doing when the lights went out?",
          "What were you do when the lights went out?", "What were you doing when the lights goed out?", "What were you doing when the light went?"] },
  spc_l3_6: { full: "I was not listening, so I did not hear the question.",
    pos: ["I didn't hear the question because I wasn't listening.", "I wasnt listening so I didnt hear the question", "I wasn't listening, so I did not hear the question."],
    neg: ["I wasn't listening, so I didn't heard the question.", "I didn't listen, so I didn't hear the question.", "I wasn't listening, so I didn't listen the question.",
          "I wasn't listening, so I wasn't hearing the question.", "I wasn't listening, so I don't hear the question.", "I wasn't hearing, so I didn't hear the question."] },
  spc_l3_7: { full: "It was raining a lot when we left school.",
    pos: ["It was raining heavily when we came out of school.", "When we left school, it was raining hard.", "It was raining a lot when we left the school"],
    neg: ["It rained a lot when we left school.", "It was raining much when we left school.", "It was raining a lot when we left the college.", "Was raining a lot when we left school.",
          "It was raining a lot when we leaved school.", "It was raining a lot when we left of school."] },
  spc_l3_8: { full: "I saw an accident when I was going to work.",
    pos: ["I saw an accident on my way to work.", "I saw an accident while I was driving to work.", "On my way to work, I saw an accident.", "When I was going to work, I saw an accident."],
    neg: ["I saw an accident when I went to work.", "I was seeing an accident when I was going to work.", "I saw an accident when I was going to the work.",
          "I see an accident when I was going to work.", "I saw a accident when I was going to work.", "I saw an accident when I was go to work."] },
  spc_l3_9: { full: "My mother was reading while my father was sleeping.",
    pos: ["While my father was sleeping, my mother was reading.", "My mum was reading while my dad was asleep.", "My mother read while my father slept."],
    neg: ["My mother was reading while my father was sleep.", "My mother were reading while my father was sleeping.", "My mother is reading while my father is sleeping.",
          "My mother was reading during my father was sleeping.", "My mother was reading while my father was sleeped.", "My mother was reading while my father sleeping."] },

  spf_l3_0: { full: "When I got home, my brother had already had dinner.",
    pos: ["When I arrived home, my brother had already eaten.", "My brother had already had dinner when I got home.", "By the time I got back, my brother had had his dinner already.",
          "When I came home my brother had already eaten dinner"],
    neg: ["When I got home, my brother already had dinner.", "When I got home, my brother has already had dinner.", "When I arrived to home, my brother had already had dinner.",
          "When I got home, my brother had already have dinner.", "When I got to home, my brother had already had dinner.", "When I got home, my brother had already dinner."] },
  spf_l3_1: { full: "When I got home, my brother left.",
    pos: ["When I arrived home, my brother went out.", "My brother left when I got home.", "When I came home my brother left"],
    neg: ["When I got home, my brother had left.", "When I got home, my brother was leaving.", "When I got home, my brother went himself.", "When I got home, my brother leaved.",
          "When I get home, my brother left.", "When I got home, my brother has left."] },
  spf_l3_2: { full: "I could not get in because I had forgotten my keys.",
    pos: ["I couldn't get into the house because I had forgotten my keys.", "I wasn't able to get in because I had forgotten the keys.", "I couldn't get in because I'd forgotten my keys",
          "I couldnt open the door because I had forgotten my keys", "I cannot... ".slice(0, 0) + "I couldn't get in as I had forgotten my keys."],
    neg: ["I couldn't get in because I forgot my keys.", "I couldn't get in because I have forgotten my keys.", "I couldn't to get in because I had forgotten my keys.",
          "I didn't can get in because I had forgotten my keys.", "I couldn't get in because I had forget my keys.", "I can't get in because I had forgotten my keys."] },
  spf_l3_3: { full: "I had never travelled by plane until that summer.",
    pos: ["I had never flown until that summer.", "I had never travelled by plane before that summer.", "I had never traveled by plane until that summer", "I'd never been on a plane until that summer."],
    neg: ["I had never travelled in plane until that summer.", "I have never travelled by plane until that summer.", "I never travelled by plane until that summer.",
          "I had never travel by plane until that summer.", "I had never travelled by plane until this summer.", "I had never flew until that summer."] },
  spf_l3_4: { full: "After we had finished the exam, we went out to celebrate.",
    pos: ["After finishing the exam, we went out to celebrate.", "We went out to celebrate after we had finished the exam.", "After we finished the exam we went out to celebrate it",
          "After we'd finished the test, we went out celebrating."],
    neg: ["After finish the exam, we went out to celebrate.", "After we had finished the exam, we had gone out to celebrate.", "After we have finished the exam, we went out to celebrate.",
          "After we had finished the exam, we go out to celebrate.", "After we had finished the exam, we went out for celebrate.", "After we had finished the exam, we went to celebrate out."] },
  spf_l3_5: { full: "When we arrived, the shop had already closed.",
    pos: ["When we got there, the shop had closed already.", "The shop had already closed when we arrived.", "When we arrived, the store had already closed"],
    neg: ["When we arrived, the shop already closed.", "When we arrived, the shop has already closed.", "When we arrived, the shop had already close.", "When we had arrived, the shop closed.",
          "When we arrived, the shop had yet closed.", "When we arrive, the shop had already closed."] },
  spf_l3_6: { full: "He knew the answer because he had read the book.",
    pos: ["He knew the answer because he'd read the book.", "He knew the answer as he had read the book."],
    neg: ["He knew the answer because he read the book.", "He was knowing the answer because he had read the book.", "He knew the answer because he had readed the book.",
          "He knowed the answer because he had read the book.", "He knew the answer because he has read the book.", "He knew the answer because had read the book."] },
  spf_l3_7: { full: "When the police arrived, the thief had escaped.",
    pos: ["When the police got there, the thief had already run away.", "The thief had escaped when the police arrived.", "By the time the police arrived, the burglar had got away."],
    neg: ["When the police arrived, the thief escaped.", "When the police arrived, the thief had escape.", "When the police arrived, the thief had ran away.",
          "When the police arrived, the thief has escaped.", "When the police had arrived, the thief escaped.", "When the police arrived, the thief was escaping."] },
  spf_l3_8: { full: "He told me that he had passed all his exams.",
    pos: ["She told me she had passed all her exams.", "He said that he had passed all his exams.", "He told me he'd passed all of his exams.", "He told me he had passed all the tests."],
    neg: ["He told me that he has passed all his exams.", "He said me that he had passed all his exams.", "He told that he had passed all his exams.",
          "He told me that he had approved all his exams.", "He told me that he had pass all his exams.", "He told me that he passed all his exams."] },
  spf_l3_9: { full: "Had you eaten before you came?",
    pos: ["Had you eaten before coming here?", "Had you had lunch before you came?", "Had you had something to eat before coming?"],
    neg: ["Did you eat before coming?", "Had you eaten before to come?", "Had you ate before you came?", "Have you eaten before you came?", "You had eaten before you came?",
          "Had you eaten after you came?"] },

  review_l3_0: { full: "Yesterday I got up at seven.",
    pos: ["I got up at seven yesterday.", "Yesterday I got up at 7 o'clock.", "Yesterday I got up at 7:00", "I got up at 7 am yesterday"],
    neg: ["Yesterday I get up at seven.", "Yesterday I have got up at seven.", "Yesterday I got me up at seven.", "Yesterday I getted up at seven.", "Yesterday I got at seven up.",
          "Yesterday I got up at eight."] },
  review_l3_1: { full: "We were watching a film when the lights went out.",
    pos: ["We were watching a movie when there was a power cut.", "When the lights went out, we were watching a film.", "We were watching a film when the power went off."],
    neg: ["We watched a film when the lights went out.", "We were seeing a film when the lights went out.", "We was watching a film when the lights went out.",
          "We were watching a film when the lights were going out.", "We were watch a film when the lights went out.", "We were watching a film when the lights go out."] },
  review_l3_2: { full: "I have never been to France.",
    pos: ["I've never been to France.", "I have never visited France.", "Ive never been in France"],
    neg: ["I have never be in France.", "I never was in France.", "I had never been to France.", "I have never went to France.", "I haven't never been to France.", "I have ever been to France."] },
  review_l3_3: { full: "When we woke up, it had already stopped snowing.",
    pos: ["When we woke up, the snow had already stopped.", "It had already stopped snowing when we woke up.", "By the time we woke up it had stopped snowing already"],
    neg: ["When we woke up, it had already stopped to snow.", "When we woke up, it already stopped snowing.", "When we waked up, it had already stopped snowing.",
          "When we woke up, had already stopped snowing.", "When we woke up, it has already stopped snowing.", "When we woke up, it had already stoped snowing."] },
  review_l3_4: { full: "Have you finished your homework yet?",
    pos: ["Have you already finished your homework?", "Have you finished the homework yet?", "Have you finished your homework?", "Have you finished your homework already?"],
    neg: ["Did you finish your homework yet?", "Have you finish your homework yet?", "Have you finished your homeworks yet?", "Have you finished yet your homework?",
          "Has you finished your homework yet?", "Had you finished your homework yet?"] },
  review_l3_5: { full: "I met my best friend in 2018.",
    pos: ["In 2018 I met my best friend.", "I met my best mate in 2018.", "I met my best friend in twenty eighteen"],
    neg: ["I knew my best friend in 2018.", "I have met my best friend in 2018.", "I met to my best friend in 2018.", "I meet my best friend in 2018.", "I met my best friend on 2018.",
          "I met my best friend in 2017."] },
  review_l3_6: { full: "While I was doing my homework, my mother was making dinner.",
    pos: ["As I was doing my homework, my mum was cooking dinner.", "My mother was making dinner while I was doing my homework.", "While I was doing the homework, my mother made dinner.",
          "While I was doing my homework my mom was preparing supper"],
    neg: ["While I was making my homework, my mother was making dinner.", "While I was doing my homework, my mother has made dinner.", "While I was do my homework, my mother was making dinner.",
          "While I were doing my homework, my mother was making dinner.", "While I was doing my homework, my mother is making dinner.", "While I was doing my homework, my mother was making the dinner of."] },
  review_l3_7: { full: "We have been living here for three years.",
    pos: ["We have lived here for three years.", "We've been living here for three years.", "For three years we have been living here.", "Weve lived here for 3 years"],
    neg: ["We are living here for three years.", "We live here for three years.", "We have been living here since three years.", "We have been living here three years.",
          "We carry three years living here.", "We have been live here for three years."] },
  review_l3_8: { full: "I had never done such a difficult exam.",
    pos: ["I had never taken such a hard exam before.", "I had never done an exam that difficult.", "I'd never sat such a difficult test before", "She had never done such a difficult exam."],
    neg: ["I have never done such a difficult exam.", "I had never made such a difficult exam.", "I had never done so difficult exam.", "I had never done a such difficult exam.",
          "I had never did such a difficult exam.", "I had never done such difficult exam."] },
  review_l3_9: { full: "What did you do last weekend?",
    pos: ["What did you do at the weekend?", "Last weekend, what did you do?", "What did you do on the weekend?"],
    neg: ["What did you do the last weekend?", "What did you did last weekend?", "What have you done last weekend?", "What you did last weekend?", "What do you do last weekend?",
          "What did you make last weekend?"] }
};
